// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// biome-ignore lint/correctness/noUnusedVariables: 型を定義するために必要
interface CloudflareEnv {
  DB: D1Database;
}
